### ISSUE TITLE
Caught exception from Twitch Vs. Minecraft (twitchmod)

### ISSUE THREAD

**Issue by RinVindor** [iCrazyBlaze/TwitchVsMinecraft#2]
I tried to install the mod via FTP to my server and this is the error I get when starting the server.

Crash Log in the link below.

https://pastebin.com/KsZCRS3p

**Comment by btarg** [comment]
Currently the mod cannot be run on the server-side. If you want to use the mod in multiplayer, your best option is to setup a LAN world. I will be fixing this in the future.
**EDIT:** The reason this is occurring is due to the GUI Screens. You are not doing anything wrong! I'll leave the issue open for now.
